# Parte 2 - Operações usuais em bases de dados

## Objetivo do capítulo

Determinadas operações são realizadas corriqueiramente em bases de dados, como por exemplo, filtrar, ordenar, agregar, sumarizar, juntar bases de dados, criar novas variáveis na base de dados etc.

Neste capítulo nosso objetivo é mostrar como usar o [`{pandas}`](https://pandas.pydata.org/) para realizar essas operações.

## Métodos vs Funções

Conforme brevemente antecipado ao final da parte anterior, o Python implementa o paradigma de programação orientada a objetos (POO). Este paradigma se diferencia da programação procedural (tradicional) por encapsular dados e procedimentos (funções) em uma única entidade denominada _objeto_. No Python, é possível utilizar (e até mesmo mesclar) tanto o paradigma tradicional quanto a POO. Quando um procedimento não está associado a um objeto ele é denominado _função_, caso esteja, é denominado _método_. Os dados associados a um objeto são seus _atributos_.

## Encadeamento de operações

O encadeamento de operações sobre um objeto do tipo tabela (`dataframe`) é muito comum em análise de dados.

Um exemplo típico de operações envolvendo um objeto do tipo `dataframe` seria: leitura de arquivo, seleção de colunas, filtragem de registros, junção com outros dados e sumarização.

Incialmente, faremos algo um pouco mais simples: leitura dos dados de um arquivo, seleção de algumas colunas de interesse e descrição estatística dos elementos das colunas selecionadas.

Para codificar a sequência de operações descrita, costuma-se mesclar os paradigmas (tradicional e POO) da seguinte maneira:

```{python}
#| eval: false
import pandas as pd

grupos = pd.read_excel("./dados/ISP2020.xlsx", sheet_name="GRUPOS")

grupos_selecionados = grupos.loc[:, ["SEGURADOS ATIVOS",
                                     "APOSENTADOS", "PENSIONISTAS"]]

grupos_selecionados.describe()
```

Podemos reescrever o código, explicitando o encadeamento de operações de modo a torná-lo mais organizado, facilitando sua leitura e compreensão, da seguinte forma:

```{python}
import pandas as pd

grupos = pd.read_excel("./dados/ISP2020.xlsx", sheet_name="GRUPOS")

(grupos
    .loc[:, ["SEGURADOS ATIVOS", "APOSENTADOS", "PENSIONISTAS"]]
    .describe())
```

Observe que o fluxo de operações agora pode ser lido de forma mais clara e natural: partindo de um conjunto de dados tabular (`grupos`), seleciona-se um subconjunto de colunas (`.loc[]`) e obtém-se estatísticas que descrevem os dados das colunas selecionadas (`.describe()`).

Caso estivéssemos utilizando a biblioteca [`{polars}`](https://github.com/pola-rs/polars) ao invés de `{pandas}`, o código seria praticamente idêntico:

```{python}
import polars as pl

grupos = pl.read_excel("./dados/ISP2020.xlsx", sheet_name="GRUPOS")

(grupos
    .select(["SEGURADOS ATIVOS", "APOSENTADOS", "PENSIONISTAS"])
    .describe())
```